### ISSUE TITLE
Scraper is obsolete; archive?

### ISSUE THREAD

**Issue by danielrheinbay** [kopf/gsack#2]
Good news: I am not sure since when, but I just noticed the official API of Abfallwirtschaft Stuttgart now includes Gelber Sack dates as well! Generate an ical URL for your place at https://service.stuttgart.de/lhs-services/aws/abfallkalender

May be it's time to archive this repo?

**Comment by kopf** [comment]
That's fantastic news!

..until another agency takes over the job of handling Stuttgart's rubbish :) 

But thanks for letting me know of this. I'll take care of it tomorrow.
